name: bia_bip
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  get: ^4.5.6
  get_storage: ^2.1.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  mask_text_input_formatter: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/